# Generated by Django 5.2.15 on 2026-06-13 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_datasource_authorization_flag'),
        ('routing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routeplan',
            name='routing_rou_client__3dbfe9_idx',
        ),
        migrations.AddField(
            model_name='routeplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routeplan',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['user', '-created_at'], name='routing_rou_user_id_017555_idx'),
        ),
    ]
