# Generated by Django 5.2.15 on 2026-06-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(default='mock', max_length=40)),
                ('license', models.CharField(blank=True, max_length=120)),
                ('is_mock', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('website', models.URLField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_sample_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='charging.datasource')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='charging.operator')),
            ],
        ),
        migrations.CreateModel(
            name='ReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=70)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability', to='charging.station')),
            ],
        ),
        migrations.CreateModel(
            name='EVSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evse_uid', models.CharField(max_length=120, unique=True)),
                ('max_power_kw', models.PositiveIntegerField()),
                ('status', models.CharField(default='available', max_length=32)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evses', to='charging.station')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kwh', models.DecimalField(decimal_places=3, max_digits=6)),
                ('session_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_estimated', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='charging.station')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(max_length=32)),
                ('max_power_kw', models.PositiveIntegerField()),
                ('evse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='charging.evse')),
            ],
            options={
                'indexes': [models.Index(fields=['connector_type', 'max_power_kw'], name='charging_co_connect_753049_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_snapshots', to='charging.datasource')),
                ('evse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_snapshots', to='charging.evse')),
            ],
            options={
                'indexes': [models.Index(fields=['observed_at', 'status'], name='charging_av_observe_26180b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='charging_st_latitud_2439bd_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['is_sample_data'], name='charging_st_is_samp_5cd612_idx'),
        ),
    ]
