# Generated by Django 5.2.15 on 2026-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_datasource_authorization_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evse',
            name='status',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
