# Generated by Django 5.2.15 on 2026-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, max_length=64)),
                ('recommendation_id', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('useful', 'Useful'), ('not_useful', 'Not useful'), ('charger_busy', 'Charger busy'), ('wrong_data', 'Wrong data'), ('wrong_price', 'Wrong price')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
