# Generated by Django 5.2.15 on 2026-06-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_route_plan_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recommendation_id',
        ),
    ]
